version: 2
jobs:
  build:
    working_directory: ~/src
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run: flutter doctor
      - run: mkdir ~/keys
      - run: echo ${KEY_PROPERTIES} | base64 --decode > ~/src/android/key.properties
      - run: echo ${JSON_KEY_DATA} | base64 --decode > ~/keys/api.json
      - run: echo ${MINESWEEPER_JKS} | base64 --decode > ~/keys/minesweeper.jks
      - run: flutter build appbundle
