version: 2
jobs:
  build:
    working_directory: ~/src
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run: flutter doctor
      - run: mkdir ~/src/android/ && cat ${KEY_PROPERTIES} | base64 --decode > ~/src/android/key.properties
      - run: mkdir ~/keys && cat ${JSON_KEY_DATA} | base64 --decode > ~/keys/api.json
      - run: flutter build appbundle
